"""initial tenant-safe GrowthOS schema

Revision ID: 20260918_0001
Revises:
"""
from alembic import op
import sqlalchemy as sa
revision="20260918_0001"
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
    op.create_table("merchants",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("business_name",sa.String(255),nullable=False),sa.Column("email",sa.String(320),nullable=False,unique=True),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("gstin",sa.String(32)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")))
    op.create_table("products",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("merchant_id",sa.Integer(),sa.ForeignKey("merchants.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("sku",sa.String(100),nullable=False),sa.Column("barcode",sa.String(100)),sa.Column("category",sa.String(100),nullable=False,server_default="General"),sa.Column("price",sa.Numeric(10,2),nullable=False),sa.Column("stock",sa.Numeric(10,3),nullable=False,server_default="0"),sa.Column("reserved_stock",sa.Numeric(10,3),nullable=False,server_default="0"),sa.Column("low_stock_threshold",sa.Numeric(10,3),nullable=False,server_default="5"),sa.Column("unit",sa.String(20),nullable=False,server_default="piece"),sa.Column("gst_percent",sa.Numeric(5,2),nullable=False,server_default="0"),sa.Column("is_deleted",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.UniqueConstraint("merchant_id","sku",name="uq_products_merchant_sku"),sa.UniqueConstraint("merchant_id","barcode",name="uq_products_merchant_barcode"),sa.CheckConstraint("stock >= 0",name="ck_products_stock_nonnegative"))
    op.create_index("ix_products_merchant_name","products",["merchant_id","name"]); op.create_index("ix_products_merchant_id","products",["merchant_id"])
    op.create_table("customers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("merchant_id",sa.Integer(),sa.ForeignKey("merchants.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("phone",sa.String(20),nullable=False),sa.Column("email",sa.String(320)),sa.Column("address",sa.String(500)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.UniqueConstraint("merchant_id","phone",name="uq_customers_merchant_phone")); op.create_index("ix_customers_merchant_phone","customers",["merchant_id","phone"])
    op.create_table("carts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("merchant_id",sa.Integer(),sa.ForeignKey("merchants.id",ondelete="CASCADE"),nullable=False),sa.Column("customer_id",sa.Integer(),sa.ForeignKey("customers.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(20),nullable=False,server_default="active"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")))
    op.create_table("cart_items",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("cart_id",sa.Integer(),sa.ForeignKey("carts.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Integer(),sa.ForeignKey("products.id"),nullable=False),sa.Column("quantity",sa.Numeric(10,3),nullable=False),sa.Column("price",sa.Numeric(10,2),nullable=False),sa.Column("reservation_expires_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("cart_id","product_id",name="uq_cart_items_cart_product"))
    op.create_table("orders",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("merchant_id",sa.Integer(),sa.ForeignKey("merchants.id",ondelete="CASCADE"),nullable=False),sa.Column("customer_id",sa.Integer(),sa.ForeignKey("customers.id"),nullable=False),sa.Column("invoice_number",sa.String(64),nullable=False),sa.Column("total_amount",sa.Numeric(12,2),nullable=False),sa.Column("gst_amount",sa.Numeric(12,2),nullable=False,server_default="0"),sa.Column("status",sa.String(20),nullable=False,server_default="draft"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.UniqueConstraint("merchant_id","invoice_number",name="uq_orders_merchant_invoice")); op.create_index("ix_orders_merchant_created_status","orders",["merchant_id","created_at","status"])
    op.create_table("order_items",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("order_id",sa.Integer(),sa.ForeignKey("orders.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Integer(),sa.ForeignKey("products.id"),nullable=False),sa.Column("quantity",sa.Numeric(10,3),nullable=False),sa.Column("price",sa.Numeric(10,2),nullable=False))
    op.create_table("inventory_movements",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("merchant_id",sa.Integer(),sa.ForeignKey("merchants.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Integer(),sa.ForeignKey("products.id"),nullable=False),sa.Column("order_id",sa.Integer(),sa.ForeignKey("orders.id")),sa.Column("movement_type",sa.String(20),nullable=False),sa.Column("quantity",sa.Numeric(10,3),nullable=False),sa.Column("note",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")))
def downgrade():
    op.drop_table("inventory_movements"); op.drop_table("order_items"); op.drop_table("orders"); op.drop_table("cart_items"); op.drop_table("carts"); op.drop_table("customers"); op.drop_table("products"); op.drop_table("merchants")
