import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { api, money } from '../api';

export default function InventoryView({ onInventoryChanged }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('All'); const [updating, setUpdating] = useState(null);
  const load = useCallback(async () => { try { setLoading(true); const data = await api('/api/products?size=100'); setItems(data.items); setError(''); } catch (err) { setError(err.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const categories = useMemo(() => ['All', ...new Set(items.map(item => item.category))], [items]);
  const filtered = items.filter(item => (category === 'All' || item.category === category) && `${item.name} ${item.sku}`.toLowerCase().includes(search.toLowerCase()));
  const low = items.filter(item => Number(item.stock_quantity) <= Number(item.low_stock_threshold));
  const replenish = async (item) => { const quantity = Math.max(Number(item.low_stock_threshold) - Number(item.stock_quantity) + 1, 1); try { setUpdating(item.id); const updated = await api(`/api/products/${item.id}/adjust-stock`, { method: 'POST', body: JSON.stringify({ quantity, direction: 'increase', note: 'Dashboard replenishment' }) }); setItems(old => old.map(product => product.id === updated.id ? updated : product)); onInventoryChanged?.(); } catch (err) { setError(err.message); } finally { setUpdating(null); } };
  return <div className="max-w-6xl mx-auto flex flex-col gap-5 text-xs">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-semibold text-white">Inventory</h1><p className="mt-1 text-[#888888]">Live product catalog and stock levels.</p></div><button onClick={load} className="rounded-md border border-[#2e2e2e] px-3 py-1.5 hover:bg-[#161616]">Refresh</button></div>
    {error && <p className="rounded-md border border-[#ff0055]/40 p-3 text-[#ffb3c9]">{error}</p>}
    <div className="grid grid-cols-2 gap-3"><Stat label="Catalog products" value={items.length} /><Stat label="Low stock" value={low.length} /></div>
    <div className="rounded-lg border border-[#1f1f1f] overflow-hidden"><div className="p-3 flex flex-wrap gap-3 border-b border-[#1f1f1f]"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search product or SKU" className="rounded-md border border-[#2e2e2e] bg-black px-3 py-1.5 outline-none" />{categories.map(value => <button key={value} onClick={() => setCategory(value)} className={`rounded-md px-2.5 py-1.5 ${category === value ? 'bg-white text-black' : 'text-[#888888] hover:bg-[#161616]'}`}>{value}</button>)}</div><table className="w-full text-left"><thead className="bg-[#0a0a0a] text-[#888888]"><tr><th className="p-3">Product / SKU</th><th className="p-3">Category</th><th className="p-3">Stock</th><th className="p-3">Price</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{filtered.map(item => { const isLow = Number(item.stock_quantity) <= Number(item.low_stock_threshold); return <tr key={item.id} className="border-t border-[#1f1f1f]"><td className="p-3 text-white"><p>{item.name}</p><p className="font-mono text-[#666666]">{item.sku}</p></td><td className="p-3 text-[#888888]">{item.category}</td><td className={isLow ? 'p-3 text-[#ff0055]' : 'p-3 text-[#00e599]'}>{item.stock_quantity} {item.unit} <span className="text-[#666666]">(min {item.low_stock_threshold})</span></td><td className="p-3 text-white">{money(item.price)}</td><td className="p-3 text-right">{isLow && <button disabled={updating === item.id} onClick={() => replenish(item)} className="rounded border border-[#2e2e2e] px-2 py-1 disabled:opacity-50">{updating === item.id ? 'Updating…' : 'Replenish'}</button>}</td></tr>; })}{!loading && !filtered.length && <tr><td colSpan="5" className="p-8 text-center text-[#666666]">No products match this filter.</td></tr>}{loading && <tr><td colSpan="5" className="p-8 text-center text-[#888888]">Loading catalog…</td></tr>}</tbody></table></div>
  </div>;
}
function Stat({ label, value }) { return <div className="rounded-lg border border-[#1f1f1f] bg-[#0a0a0a] p-4"><p className="text-[#888888]">{label}</p><p className="mt-2 font-mono text-2xl text-white">{value}</p></div>; }
